name: deploy guides.18f.org

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: deploy
    uses: team18f/site/.github/workflows/deploy.yaml@main
    with:
      repo: team18f/guides
    secrets:
      token: ${{ secrets.CLONE_PAT }}
